name: Build Ziqni

on:
  push:
    branches:
      - blazzio

jobs:
  build-image:
    runs-on: [hetzner,heavy]
    timeout-minutes: 10
    name: Build and push docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate build ID
        id: build_id
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_REF=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "BUILD_SHA=${sha}" >> $GITHUB_OUTPUT
          echo "BUILD_TS=${ts}" >> $GITHUB_OUTPUT
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gaembla.com
          username: deploy
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        run: |
          docker buildx build --no-cache -t registry.gaembla.com/gaembla/ziqni-member-hub:${{steps.build_id.outputs.BUILD_ID}} -f Dockerfile .
          docker push registry.gaembla.com/gaembla/ziqni-member-hub:${{steps.build_id.outputs.BUILD_ID}}
